### ISSUE TITLE
Falsche Nachricht wenn Gruppenleiter "Verlassen" unter eine Willkommensnachricht drückt

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/halloween#14]
Unter der Willkommensnachricht "{newmember} ist jetzt Teil der Crew! Herzlich willkommen." 
steht der [Verlassen]-Knopf, falls die Person sich umentscheidet und wieder raus möchte. 
  
Drückt die Person den Knopf, ist sie **raus** (auch wenn das Abenteuer schon begonnen hat, Süßigkeiten *und vermutlich Mut - ungetestet -* werden bis zum Zeitpunkt des Verlassens gesammelt/ verloren). 
So weit funktioniert es. ✅

Drückt allerdings die **Gruppenleitung** den [Verlassen] Knopf der Person, erscheint folgende Nachricht:
> Nur {Gruppenleitung} darf diesen Button bedienen. Wenn du die Gruppe verlassen willst, versuche es mit `/leave-group`

Die Nachricht ist ziemlich irreführend, müsste gefixt werden. 
💡 Möglicherweise sollte statt {Gruppenleitung} der Name des in der Nachricht begrüßten Mitglied stehen? 
-> Sollte die Gruppenleitung drücken, wäre vielleicht ein direkter Hinweis darauf dabei sein, dass `/leave-group` nicht klappen wird.
Dann erscheint nämlich: 
> Du darfst deine Gruppe nicht im Stich lassen. Als Gruppenleiterin kannst du sie höchstens beenden, aber nicht verlassen.

Noch nicht getestet: 
- [ ] Was passiert wenn ein Teammitglied den Knopf drückt?

**Comment by dnns01** [comment]
Ja, da wird tatsächlich fälschlicherweise der User angegeben, der den Button gedrückt hat

```python
    async def on_leave(self, button: discord.ui.Button, interaction: Interaction, value=None):
        thread_id = interaction.channel_id
        player_id = interaction.user.id
        msg_player = interaction.message.mentions[0]

        if msg_player.id == player_id:
            self.leave_group(thread_id, player_id)
            await interaction.response.send_message(f"<@{player_id}> hat die Gruppe verlassen.")
            await interaction.message.edit(view=self.get_leave_view(disabled=True))
        else:
            await interaction.response.send_message(
                f"Nur <@{player_id}> darf diesen Button bedienen. Wenn du die Gruppe "
                f"verlassen willst, versuche es mit `/leave-group`", ephemeral=True)
```
`player_id` ist die Person, die auf den Button gedrückt hat. Sollte stattdessen `msg_player.id` sein..
